# Generated by Django 5.2 on 2025-11-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_newsleters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newsleters',
            new_name='Newsletter',
        ),
    ]
